import turtle

def space():
    turtle.penup()
    turtle.setheading(0)
    turtle.forward(10)
    turtle.pendown()

def turtle0():
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(30)
    space()

def turtle1():
    turtle.left(90)
    turtle.forward(50)
    turtle.left(180)
    turtle.forward(50)
    space()

def turtle2():
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(30)
    space()

def turtle3():
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.left(180)
    space()

def turtle4():
  turtle.penup()
  turtle.left(90)
  turtle.forward(50)
  turtle.pendown()
  turtle.left(180)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(180)
  turtle.forward(50)
  turtle.left(90)
  space()

def turtle5():
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.left(180)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.left(90)
  space()

def turtle6():
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.left(180)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(50)
  turtle.left(90)
  turtle.forward(30)
  space()

def turtle7():
  turtle.penup()
  turtle.left(90)
  turtle.forward(50)
  turtle.pendown()
  turtle.right(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(50)
  turtle.left(90)
  space()

def turtle8():
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  space()

def turtle9():
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(50)
  turtle.left(90)
  space()
