import turtle

def turtleK():
    turtle.left(90)
    turtle.forward(50)
    turtle.backward(25)
    turtle.right(50)
    turtle.forward(39)
    turtle.backward(39)
    turtle.right(80)
    turtle.forward(39)
    turtle.backward(39)
    turtle.right(50)
    turtle.forward(25)
    turtle.penup()
    turtle.left(90)
    turtle.forward(30)
    turtle.forward(10)
    turtle.pendown()

def turtleL():
    turtle.left(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

def turtleM():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(163.3)
    turtle.forward(52.2)
    turtle.left(146.6)
    turtle.forward(52.2)
    turtle.right(163.3)
    turtle.forward(50)
    turtle.penup()
    turtle.left(90)
    turtle.forward(10)
    turtle.pendown()

def turtleN():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(149)
    turtle.forward(58.3)
    turtle.left(149)
    turtle.forward(50)
    turtle.backward(50)
    turtle.penup()
    turtle.right(90)
    turtle.forward(10)
    turtle.pendown()

def turtleO():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(180)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

def turtleP():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.penup()
    turtle.left(90)
    turtle.forward(40)
    turtle.pendown()

def turtleQ():
    turtle.left(90)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(14.14)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(14.14)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(14.14)
    turtle.right(45)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(14.14)
    turtle.backward(14.14)
    turtle.right(135)
    turtle.forward(10)
    turtle.left(45)
    turtle.forward(7.07)
    turtle.left(90)
    turtle.forward(7.07)
    turtle.backward(14.14)
    turtle.right(135)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

def turtleR():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(135)
    turtle.forward(42.42)
    turtle.left(45)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

def turtleS():
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(7.07)
    turtle.left(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(7.07)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.penup()
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.pendown()

def turtleT():
    turtle.left(90)
    turtle.penup()
    turtle.forward(50)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(30)
    turtle.backward(15)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.penup()
    turtle.forward(25)
    turtle.pendown()

def turtleU():
    turtle.left(90)
    turtle.forward(50)
    turtle.backward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.backward(50)
    turtle.right(90)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

def turtleV():
    turtle.left(90)
    turtle.penup()
    turtle.forward(50)
    turtle.right(163.3)
    turtle.pendown()
    turtle.forward(52.2)
    turtle.left(146.6)
    turtle.forward(52.2)
    turtle.right(163.3)
    turtle.penup()
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.pendown()

def turtleW():
    turtle.left(90)
    turtle.forward(50)
    turtle.left(180)
    turtle.forward(50)
    turtle.left(163.3)
    turtle.forward(52.2)
    turtle.right(146.6)
    turtle.forward(52.2)
    turtle.left(163.3)
    turtle.forward(50)
    turtle.penup()
    turtle.backward(50)
    turtle.right(90)
    turtle.forward(10)
    turtle.pendown()

def turtleX():
    turtle.left(59)
    turtle.forward(58.3)
    turtle.backward(29.15)
    turtle.left(62)
    turtle.forward(29.15)
    turtle.backward(58.3)
    turtle.right(121)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

if __name__ == '__main__':
    1
    #Section for code you want run only if this is the main process