import turtle

def turtleA():
    turtle.left(73)
    turtle.forward(52)
    turtle.right(73*2)
    turtle.forward(52)
    turtle.left(180)
    turtle.forward(23)
    turtle.left(73)
    turtle.forward(19)
    turtle.penup()
    turtle.left(73)
    turtle.forward(23)
    turtle.setheading(0)
    turtle.forward(40)
    turtle.pendown()

def turtleB():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(7)
    turtle.left(90)
    turtle.forward(7)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(25)
    turtle.penup()
    turtle.forward(5)
    turtle.right(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(10)
    turtle.pendown()

def turtleC():
    turtle.penup()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(15)
    turtle.left(45)
    turtle.forward(15)
    turtle.left(45)
    turtle.forward(28)
    turtle.left(45)
    turtle.forward(15)
    turtle.left(45)
    turtle.forward(15)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

def turtleD():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(24)
    turtle.right(45)
    turtle.forward(8)
    turtle.right(45)
    turtle.forward(39)
    turtle.right(45)
    turtle.forward(8)
    turtle.right(45)
    turtle.forward(24)
    turtle.left(180)
    turtle.penup()
    turtle.forward(40)
    turtle.pendown()

def turtleE():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.penup()
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(5)
    turtle.pendown()
    turtle.forward(25)
    turtle.left(90)
    turtle.penup()
    turtle.forward(25)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(30)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

def turtleF():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.penup()
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(5)
    turtle.pendown()
    turtle.forward(25)
    turtle.left(90)
    turtle.penup()
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(40)
    turtle.pendown()

def turtleG():
    turtle.penup()
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(6)
    turtle.right(135)
    turtle.pendown()
    turtle.forward(8)
    turtle.left(45)
    turtle.forward(9)
    turtle.left(45)
    turtle.forward(21)
    turtle.left(45)
    turtle.forward(25)
    turtle.left(45)
    turtle.forward(14)
    turtle.left(45)
    turtle.forward(10)
    turtle.left(45)
    turtle.forward(14)
    turtle.left(45)
    turtle.forward(8)
    turtle.left(90)
    turtle.forward(8)
    turtle.penup()
    turtle.setheading(0)
    turtle.forward(14)
    turtle.right(90)
    turtle.forward(16)
    turtle.left(90)
    turtle.forward(10)
    turtle.pendown()

def turtleH():
    turtle.left(90)
    turtle.forward(50)
    turtle.left(180)
    turtle.penup()
    turtle.forward(25)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(30)
    turtle.penup()
    turtle.left(90)
    turtle.forward(25)
    turtle.left(180)
    turtle.pendown()
    turtle.forward(50)
    turtle.penup()
    turtle.left(90)
    turtle.forward(10)
    turtle.pendown()

def turtleI():
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.penup()
    turtle.forward(15)
    turtle.left(180)
    turtle.pendown()
    turtle.forward(30)
    turtle.penup()
    turtle.right(180)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(15)
    turtle.penup()
    turtle.forward(10)
    turtle.pendown()

def turtleJ():
    turtle.penup()
    turtle.left(90)
    turtle.forward(3)
    turtle.right(135)
    turtle.pendown()
    turtle.forward(5)
    turtle.left(45)
    turtle.forward(5)
    turtle.forward(5)
    turtle.left(45)
    turtle.forward(5)
    turtle.left(45)
    turtle.forward(47)
    turtle.left(90)
    turtle.penup()
    turtle.forward(15)
    turtle.left(180)
    turtle.pendown()
    turtle.forward(30)
    turtle.penup()
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()

if __name__ == '__main__':
    1
    #Section for code you want run only if this is the main process