import turtle

def turtleA():
    turtle.left(73)
    turtle.forward(52)
    turtle.right(73*2)
    turtle.forward(52)
    turtle.left(180)
    turtle.forward(23)
    turtle.left(73)
    turtle.forward(19)
    turtle.penup()
    turtle.left(73)
    turtle.forward(23)
    turtle.setheading(0)
    turtle.forward(40)
    turtle.pendown()

turtleA()

def turtleB():
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(22)
    turtle.right(45)
    turtle.forward(4)
    turtle.left(90)
    turtle.forward(4)
    turtle.right(45)
    turtle.forward(22)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(27)
    turtle.penup()
    turtle.forward(3)
    turtle.right(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(10)

turtleB()

turtle.mainloop()