import turtle
turtle.screensize(canvwidth=None, canvheight=None, bg=None)

def space():
    turtle.penup()
    turtle.setheading(0)
    turtle.forward(10)
    turtle.pendown()

def make_0():
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(180)

def make_1():
    turtle.left(90)
    turtle.forward(50)
    turtle.left(180)
    turtle.forward(50)

def make_2():
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(30)

def make_3():
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(25)
    turtle.left(180)

def make_4():
  turtle.penup()
  turtle.left(90)
  turtle.forward(50)
  turtle.pendown()
  turtle.left(180)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(180)
  turtle.forward(50)
  turtle.left(90)

def make_5():
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.left(180)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.left(90)

def make_6():
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.left(180)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(50)
  turtle.left(90)
  turtle.forward(30)

def make_7():
  turtle.penup()
  turtle.left(90)
  turtle.forward(50)
  turtle.pendown()
  turtle.right(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(50)
  turtle.left(90)

def make_8():
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)

def make_9():
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(25)
  turtle.right(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(50)
  turtle.left(90)


make_1()
space()
make_2()
space()
make_3()
space()
make_4()
space()
make_5()
space()
make_6()
space()
make_7()
space()
make_8()
space()
make_9()
space()
make_0()

turtle.mainloop()
